# Generated by Django 4.2 on 2026-01-06 07:13

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeAbout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainabout',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='mainabout',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainabout',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='mainabout',
            name='title',
        ),
    ]
